name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run action
      id: summary_action
      uses: Akshay090/github-action-text-summarization@master
      with:
        path: path/to/textFile.txt

    - name: Check outputs
      run: |
         echo "Text summary: ${{ steps.summary_action.outputs.summary }}"