name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: subhashshell/react-coverage-report-action@v1
              with:
                test-script: yarn test
                skip-step: all