name: Publish
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
        registry-url: https://npm.pkg.github.com/
        scope: '@subhashshell'
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}